name = "plausible"
version = "0.1.0"
defaultTargets = ["Plausible"]
testRunner = "Test"

[[lean_lib]]
name = "Test"

[[lean_lib]]
name = "Plausible"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.19.0-rc2"

[[require]]
name = "Qq"
scope = "leanprover-community"
rev = "v4.19.0-rc2"
